version: "3.9"

services:
  web:
    build: .
    container_name: django_app
    command: gunicorn lingua_market.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3
    expose:
      - "8000"

  caddy:
    image: caddy:2-alpine
    container_name: caddy_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - web
