version: "3.9"

services:
  web:
    build: .
    container_name: django_app
    command: gunicorn project_name.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3
    expose:
      - "8000"

  caddy:
    build:
      context: .
      dockerfile: Dockerfile.caddy
    container_name: caddy_proxy
    ports:
      - "80:80"
    volumes:
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - web
